src/main/java/dnd/dnd10_backend/Dnd10BackendApplication.java

set: db 설정

---

src/main/java/dnd/dnd10_backend/config/jwt/JwtProperties.java

fix: 토큰 유효기간 변경

---

src/main/java/dnd/dnd10_backend/config/CorsConfig.java
src/main/java/dnd/dnd10_backend/user/controller/UserController.java

feat/#7-user-manage
front에서 통신시 발생하는 cors에러를 해결하기 위해서 CorsConfig파일 내 수정

fix: cors에러 수정

---

src/main/java/dnd/dnd10_backend/config/jwt/JwtProperties.java

feat/#7-user-manage -> develop
토큰 만료기간을 access token은 5분 refresh token은 7분으로 수정하였습니다.

chore: 토큰 만료기간 수정

---

src/main/java/dnd/dnd10_backend/config/CorsConfig.java

feat/#7-user-manage -> develop
cors에러 해결

fix: cors 에러 해결

---

src/main/java/dnd/dnd10_backend/user/controller/TokenController.java
src/main/java/dnd/dnd10_backend/user/controller/UserController.java

feat/#7-user-manage -> develop
자잘한 코드 변경 
ex) ResponseEntity<> -> ResponseEntity

chore: 자잘한 코드 수정

---

src/main/java/dnd/dnd10_backend/Dnd10BackendApplication.java
src/main/java/dnd/dnd10_backend/checkList/controller/CheckListController.java
src/main/java/dnd/dnd10_backend/checkList/domain/CheckList.java
src/main/java/dnd/dnd10_backend/checkList/dto/request/CheckListRequestDto.java
src/main/java/dnd/dnd10_backend/checkList/dto/request/DeleteCheckListRequestDto.java
src/main/java/dnd/dnd10_backend/checkList/dto/request/SearchCheckListRequestDto.java
src/main/java/dnd/dnd10_backend/checkList/dto/request/UpdateCheckListRequestDto.java
src/main/java/dnd/dnd10_backend/checkList/dto/response/CheckListResponseDto.java
src/main/java/dnd/dnd10_backend/checkList/dto/response/WorkCheckListResponseDto.java
src/main/java/dnd/dnd10_backend/checkList/repository/CheckListRepository.java
src/main/java/dnd/dnd10_backend/checkList/service/CheckListService.java
src/main/java/dnd/dnd10_backend/common/domain/enums/CodeStatus.java
src/main/java/dnd/dnd10_backend/config/jwt/JwtRequestFilter.java
src/main/java/dnd/dnd10_backend/user/controller/TokenController.java
src/main/java/dnd/dnd10_backend/user/controller/UserController.java
src/main/java/dnd/dnd10_backend/user/service/TokenService.java

feat/#29-check ->develop
소셜 로그인 리다이렉트 uri를 isLocal이라는 param을 보고 결정해주는 걸로 변경했습니다.

fix: redirect_uri 변경

---

src/main/java/dnd/dnd10_backend/checkList/controller/CheckListController.java
src/main/java/dnd/dnd10_backend/checkList/domain/CheckList.java
src/main/java/dnd/dnd10_backend/checkList/repository/CheckListRepository.java
src/main/java/dnd/dnd10_backend/checkList/service/CheckListService.java

feat/#29-check -> develop
- 체크리스트 조회시 정렬 조건을 추가하였습니다 
- 체크리스트 조회 api에서 날짜를 받아올 때 RequestBody로 받아오던 것을  RequestParam으로 변경하였습니다.

chore: 체크리스트 조회 변경

---

src/main/java/dnd/dnd10_backend/checkList/service/CheckListService.java
src/main/java/dnd/dnd10_backend/common/domain/enums/CodeStatus.java

feat/#29-check -> develop
- 체크리스트 삭제 및 업데이트 시 사용자가 체크리스트를 작성한 사람인지 확인하도록 변경

fix: 삭제 업데이트 시 사용자 확인

---

src/main/java/dnd/dnd10_backend/calendar/controller/CalendarController.java
src/main/java/dnd/dnd10_backend/calendar/service/CalendarService.java

fix/#28-calendar -> develop
GET, DELETE 요청 파라미터 수정

fix: GET, DELETE 요청 파라미터 수정

---

src/main/java/dnd/dnd10_backend/common/domain/enums/CodeStatus.java

chore: 중복 라인 제거

---

src/main/java/dnd/dnd10_backend/user/domain/User.java
src/main/java/dnd/dnd10_backend/user/service/TokenService.java

feat/#7-user-manage -> develop
- 사용자의 프로필을 식별할 수 있는 필드 추가
- 카카오에서 프로필 사진 받아오는 부분 삭제

feat: 유저 프로필 필드 추가

---

src/main/java/dnd/dnd10_backend/checkList/domain/CheckList.java
src/main/java/dnd/dnd10_backend/checkList/repository/CheckListRepository.java
src/main/java/dnd/dnd10_backend/checkList/service/CheckListService.java

fix/#29-check -> develop
- checkList 조회 시 정렬 조건을 변경하였습니다.

fix: 체크리스트 정렬 조건 추가

---

src/main/java/dnd/dnd10_backend/calendar/controller/CalendarController.java

- [x ] 버그 수정
fix:#28-calendar -> develop
subString index 수정

fix: subString index 수정

---

src/main/java/dnd/dnd10_backend/Inventory/controller/InventoryController.java
src/main/java/dnd/dnd10_backend/Inventory/domain/Inventory.java
src/main/java/dnd/dnd10_backend/Inventory/domain/enums/Category.java
src/main/java/dnd/dnd10_backend/Inventory/dto/response/InventoryResponseDto.java
src/main/java/dnd/dnd10_backend/Inventory/repository/InventoryRepository.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryService.java
src/main/java/dnd/dnd10_backend/common/domain/enums/CodeStatus.java
src/main/java/dnd/dnd10_backend/store/domain/Store.java
src/main/java/dnd/dnd10_backend/store/repository/StoreRepository.java
src/main/java/dnd/dnd10_backend/user/controller/UserController.java
src/main/java/dnd/dnd10_backend/user/domain/User.java
src/main/java/dnd/dnd10_backend/user/dto/response/UserResponseDto.java
src/main/java/dnd/dnd10_backend/user/repository/UserRepository.java
src/main/java/dnd/dnd10_backend/user/service/UserService.java

feat/#30-inventory-manage -> develop
- 시재 조회 기능을 추가하였습니다.
- Store 엔티티를 추가하였습니다.
- 사용자 등록 및 수정 시 존재하지 않는 편의점은 Store에 추가되도록 수정하였습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/30

feat:시재 조회 기능 추가

---

src/main/java/dnd/dnd10_backend/calendar/controller/CalendarController.java

feat/login -> dev
근무시간 변수명 수정, api 요청 변경

fix: 근무시간 변수명 수정, api 요청 변경

---

src/main/java/dnd/dnd10_backend/calendar/controller/CalendarController.java
src/main/java/dnd/dnd10_backend/calendar/domain/TimeCard.java
src/main/java/dnd/dnd10_backend/calendar/dto/request/TimeCardCreateDto.java
src/main/java/dnd/dnd10_backend/calendar/dto/response/TimeCardResponseDto.java
src/main/java/dnd/dnd10_backend/calendar/repository/TimeCardRepository.java
src/main/java/dnd/dnd10_backend/calendar/service/CalendarService.java

fix: userProfileCode 추가 및 workPlace storeName으로 수정

fix: userProfileCode 추가 및 workPlace storeName으로 수정

---

src/main/java/dnd/dnd10_backend/Dnd10BackendApplication.java
src/main/java/dnd/dnd10_backend/Inventory/controller/InventoryController.java
src/main/java/dnd/dnd10_backend/Inventory/domain/Inventory.java
src/main/java/dnd/dnd10_backend/Inventory/domain/InventoryUpdateRecord.java
src/main/java/dnd/dnd10_backend/Inventory/dto/response/InventoryRecordListResponseDto.java
src/main/java/dnd/dnd10_backend/Inventory/dto/response/InventoryResponseDto.java
src/main/java/dnd/dnd10_backend/Inventory/repository/InventoryUpdateRecordRepository.java
src/main/java/dnd/dnd10_backend/Inventory/service/DefaultInventoryService.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryRecordService.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryService.java
src/main/java/dnd/dnd10_backend/calendar/repository/TimeCardRepository.java
src/main/java/dnd/dnd10_backend/user/dto/response/UserResponseDto.java

feat/#30-inventory-manage -> develop
- 시재 기록을 조회 할 수 있도록 추가하였습니다.
- 시재 기록이 작성된 지 60일이 넘어가면 삭제되도록 변경하였습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/30

feat:시재 기록 조회 기능 추가

---

src/main/java/dnd/dnd10_backend/Inventory/controller/InventoryController.java
src/main/java/dnd/dnd10_backend/Inventory/dto/response/InventoryRecordResponseDto.java
src/main/java/dnd/dnd10_backend/Inventory/repository/InventoryUpdateRecordRepository.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryRecordService.java

feat/#30-inventory-manage -> develop
- 시재 기록 조회 시 카테고리로 조회 할 수 있도록 변경
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/30

feat: 시재 기록 조회 조건 추가

---

src/main/java/dnd/dnd10_backend/calendar/controller/CalendarController.java
src/main/java/dnd/dnd10_backend/calendar/controller/SalaryController.java
src/main/java/dnd/dnd10_backend/calendar/domain/TimeCard.java
src/main/java/dnd/dnd10_backend/calendar/dto/request/TimeCardCreateDto.java
src/main/java/dnd/dnd10_backend/calendar/dto/response/SalaryDetailResponseDto.java
src/main/java/dnd/dnd10_backend/calendar/dto/response/SalaryResponseDto.java
src/main/java/dnd/dnd10_backend/calendar/dto/response/StoreSalaryResponseDto.java
src/main/java/dnd/dnd10_backend/calendar/service/SalaryService.java
src/main/java/dnd/dnd10_backend/common/domain/enums/CodeStatus.java
src/main/java/dnd/dnd10_backend/user/service/UserService.java

feat/#53-salary -> develop
알바생, 점장 급여 조회 기능을 개발했습니다
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/53

feat: 알바생, 점장 급여 조회 기능 개발

---

src/main/java/dnd/dnd10_backend/Inventory/service/InventoryService.java
src/main/java/dnd/dnd10_backend/common/domain/SingleResponse.java

chore/#30-inventory-response -> develop
- 시재 기록 조회 시 발생하는 exception에 대한 response message 및 code 변경

chore: 시재 기록 조회 시 exception에 대한 codestatus추가

---

src/main/java/dnd/dnd10_backend/Inventory/repository/InventoryRepository.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryRecordService.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryService.java

fix/#30-inventory-update -> develop
- 시재 업데이트 및 조회 시 발생하는 에러 해결
- 시재 업데이트 시 편의점 조건을 걸지 않아 발생하는 에러 해결
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/30

fix: 시재 업데이트 시 에러 해결

---

src/main/java/dnd/dnd10_backend/checkList/domain/DefaultCheckList.java
src/main/java/dnd/dnd10_backend/checkList/repository/DefaultCheckListRepository.java
src/main/java/dnd/dnd10_backend/checkList/service/CheckListService.java
src/main/java/dnd/dnd10_backend/checkList/service/DefaultCheckListService.java

feat/#29-default-checkList -> develop
- 기본 시재를 매주 일요일마다 사용자의 근무일자를 보고 등록하는 기능을 구현하였습니다.
- checkListService의 불필요한 코드를 삭제하였습니다. (사용하지 않는 repository가 선언되어있는 것)

feat: 기본 시재를 등록해주는 기능 구현

---

src/main/java/dnd/dnd10_backend/Inventory/service/DefaultInventoryService.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryRecordService.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryService.java
src/main/java/dnd/dnd10_backend/calendar/service/CalendarService.java
src/main/java/dnd/dnd10_backend/checkList/service/CheckListService.java
src/main/java/dnd/dnd10_backend/checkList/service/DefaultCheckListService.java
src/main/java/dnd/dnd10_backend/user/service/CustomUserDetailsService.java
src/main/java/dnd/dnd10_backend/user/service/TokenService.java
src/main/java/dnd/dnd10_backend/user/service/UserService.java

feat/#29-default-checkList
- 사용자에게 등록되지 않은 출근 일자에 출근할 경우 기본 체크리스트가 생성되도록 구현하였습니다.
- 코드의 통일성을 위해 일부 코드가 변경되었습니다.

feat: 원래 근무 일자가 아닐때의 출근 시 체크리스트 생성 기능 구현

---

src/main/java/dnd/dnd10_backend/Inventory/controller/InventoryController.java
src/main/java/dnd/dnd10_backend/Inventory/service/DefaultInventoryService.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryRecordService.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryService.java
src/main/java/dnd/dnd10_backend/checkList/controller/CheckListController.java
src/main/java/dnd/dnd10_backend/checkList/service/CheckListService.java
src/main/java/dnd/dnd10_backend/checkList/service/DefaultCheckListService.java
src/main/java/dnd/dnd10_backend/config/SecurityConfig.java
src/main/java/dnd/dnd10_backend/config/jwt/JwtRequestFilter.java
src/main/java/dnd/dnd10_backend/user/controller/TokenController.java
src/main/java/dnd/dnd10_backend/user/controller/UserController.java
src/main/java/dnd/dnd10_backend/user/service/CustomUserDetailsService.java
src/main/java/dnd/dnd10_backend/user/service/TokenService.java
src/main/java/dnd/dnd10_backend/user/service/UserService.java

develop -> develop
- 코드 스타일 통일
- @AutoWired삭제

refactor: 코드 스타일 통일

---

src/main/java/dnd/dnd10_backend/checkList/repository/CheckListRepository.java
src/main/java/dnd/dnd10_backend/checkList/service/CheckListService.java
src/main/java/dnd/dnd10_backend/checkList/service/DefaultCheckListService.java

feat/#29-check-delete -> develop
- 서버 시간을 기준으로 매주 일요일에 `일주일전 금요일까지의 체크리스트`를 모두 삭제하는 기능을 구현하였습니다.

feat: 지난주 체크리스트 삭제 기능 추가

---

src/main/java/dnd/dnd10_backend/store/controller/StoreController.java
src/main/java/dnd/dnd10_backend/store/domain/Store.java
src/main/java/dnd/dnd10_backend/store/dto/response/StoreResponseDto.java
src/main/java/dnd/dnd10_backend/store/service/StoreService.java
src/main/java/dnd/dnd10_backend/user/dto/request/UserSaveRequestDto.java
src/main/java/dnd/dnd10_backend/user/dto/response/UserStoreResponseDto.java
src/main/java/dnd/dnd10_backend/user/service/UserService.java

feat/#63-user-page
- 사용자의 지점에 속한 사람들의 정보를 조회 할 수 있는 기능 구현
- 새로운 지점 등록 시 주소를 저장하도록 수정
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/64

feat: 사용자 지점 정보 조회 기능 구현

---

src/main/java/dnd/dnd10_backend/calendar/service/CalendarService.java

fix/#29-checkList-error
- 프론트에서 받아오는 date를 백에서 사용가능한 LocalDate Format으로 변경할 수 있도록 하였습니다.

fix: 출근 시 발생하는 에러 해결

---

src/main/java/dnd/dnd10_backend/Inventory/domain/InventoryUpdateRecord.java
src/main/java/dnd/dnd10_backend/Inventory/dto/response/InventoryRecordListResponseDto.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryRecordService.java
src/main/java/dnd/dnd10_backend/checkList/repository/CheckListRepository.java
src/main/java/dnd/dnd10_backend/common/domain/enums/CodeStatus.java
src/main/java/dnd/dnd10_backend/user/controller/UserController.java
src/main/java/dnd/dnd10_backend/user/domain/User.java
src/main/java/dnd/dnd10_backend/user/dto/response/UserResponseDto.java
src/main/java/dnd/dnd10_backend/user/service/UserService.java

fix/#29-checkList-orderBy
- 체크리스트 정렬 순서 변경
- 시재 기록과 user에 대한 연관관계 삭제

fix: checkList orderBy 수정

---

src/main/java/dnd/dnd10_backend/Inventory/service/InventoryService.java
src/main/java/dnd/dnd10_backend/calendar/domain/TimeCard.java
src/main/java/dnd/dnd10_backend/calendar/domain/UserTimeCard.java
src/main/java/dnd/dnd10_backend/calendar/dto/request/TimeCardCreateDto.java
src/main/java/dnd/dnd10_backend/calendar/repository/TimeCardRepository.java
src/main/java/dnd/dnd10_backend/calendar/repository/UserTimeCardRepository.java
src/main/java/dnd/dnd10_backend/calendar/service/CalendarService.java
src/main/java/dnd/dnd10_backend/calendar/service/SalaryService.java
src/main/java/dnd/dnd10_backend/checkList/service/CheckListService.java
src/main/java/dnd/dnd10_backend/user/domain/User.java

feat/#28-UserTimeCard -> develop
UserTimeCard 객체 구현으로 User 삭제 시에도 TimeCard 조회 가능

feat: UserTimeCard 구현

---

src/main/java/dnd/dnd10_backend/Inventory/domain/InventoryUpdateRecord.java
src/main/java/dnd/dnd10_backend/checkList/service/DefaultCheckListService.java

fix/#30-inventory-entity -> develop
- inventory update record에서 저장할 필요가 없는 column을 삭제했습니다.

fix: inventory update record entity 변경

---

src/main/java/dnd/dnd10_backend/auth/domain/Token.java
src/main/java/dnd/dnd10_backend/user/domain/User.java

fix/#64-user-delete -> develop
- token과 user 도메인의 연관 관계를 추가 및 수정하였습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/64

fix: 사용자 탈퇴 관련 에러 수정

---

src/main/java/dnd/dnd10_backend/user/controller/TokenController.java
src/main/java/dnd/dnd10_backend/user/controller/UserController.java
src/main/java/dnd/dnd10_backend/user/domain/User.java
src/main/java/dnd/dnd10_backend/user/dto/request/UserSaveRequestDto.java
src/main/java/dnd/dnd10_backend/user/dto/response/UserCreateResponseDto.java
src/main/java/dnd/dnd10_backend/user/dto/response/UserResponseDto.java
src/main/java/dnd/dnd10_backend/user/repository/UserRepository.java
src/main/java/dnd/dnd10_backend/user/service/TokenService.java
src/main/java/dnd/dnd10_backend/user/service/UserService.java

fix/#73-login-error -> develop
- 소셜 가입 시 발생하는 에러를 해결하였습니다.
- userService의 사용자 등록과 업데이트 함수를 분리하였습니다.
- user 도메인에 wage(시급)에 대한 column을 추가하였습니다.
- 사용자 등록 및 수정 시 wage(시급)에 대한 정보를 받을 수 있도록 dto를 수정하였습니다.
- 사용자 회원가입 response dto를 만들었습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/73

fix: 소셜 가입 시 발생하는 에러해결

---

src/main/java/dnd/dnd10_backend/calendar/controller/CalendarController.java
src/main/java/dnd/dnd10_backend/calendar/domain/UserTimeCard.java
src/main/java/dnd/dnd10_backend/calendar/dto/request/UpdateTimeCardRequestDto.java
src/main/java/dnd/dnd10_backend/calendar/dto/response/StoreSalaryResponseDto.java
src/main/java/dnd/dnd10_backend/calendar/dto/response/TimeCardResponseDto.java
src/main/java/dnd/dnd10_backend/calendar/service/CalendarService.java
src/main/java/dnd/dnd10_backend/calendar/service/SalaryService.java

feat/#28-TimeCard -> develop
중복 근무에 대한 이슈로 인해 수정 로직 수정, 시급 값 변경

fix: 수정 로직 수정 및 급여 값 변경

---

src/main/java/dnd/dnd10_backend/checkList/repository/CheckListRepository.java
src/main/java/dnd/dnd10_backend/checkList/service/CheckListService.java
src/main/java/dnd/dnd10_backend/checkList/service/DefaultCheckListService.java
src/main/java/dnd/dnd10_backend/user/domain/User.java

feat/#77-default-check -> develop
- 사용자 등록 및 수정 시 기본 체크리스트를 추가하도록 기능을 추가하였습니다.
- 체크리스트의 정렬 순서를 checkIdx를 내림차순으로 보여주도록 수정하였습니다.
- 이번주를 기준으로 체크리스트 남아있는지 확인하는 함수인 checkWeek함수의 날짜 확인 부분의 에러를 수정하였습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/77

feat: 사용자 등록 및 수정 시 기본 체크리스트 등록 기능 구현

---

src/main/java/dnd/dnd10_backend/calendar/controller/CalendarController.java
src/main/java/dnd/dnd10_backend/calendar/service/CalendarService.java

fix/#28-TimeCardDelete -> develop
삭제 요청 인자를 id 값으로 변경

fix: timeCard 삭제 요청 인자 변경

---

src/main/java/dnd/dnd10_backend/checkList/domain/CheckList.java
src/main/java/dnd/dnd10_backend/checkList/repository/CheckListRepository.java
src/main/java/dnd/dnd10_backend/checkList/service/CheckListService.java

fix/#29-order-check -> develop
- 체크리스트 정렬 조건을 변경하였습니다.
- 체크가 될 때 시간 컬럼을 checkList 엔티티에 추가하였습니다.
- 체크리스트의 상태가 N => Y로 변경될 때 체크시간을 변경하도록 수정하였습니다.

fix: 체크리스트 정렬 변경

---

src/main/java/dnd/dnd10_backend/user/service/UserService.java

feat/#77-default-check -> develop
- 사용자 등록 및 업데이트 시 기본 체크리스트 추가될 수 있도록 구현하였습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/77

feat: 사용자 등록 및 업데이트 시 기본 체크리스트 추가

---

src/main/java/dnd/dnd10_backend/Inventory/controller/InventoryController.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryService.java
src/main/java/dnd/dnd10_backend/common/domain/enums/CodeStatus.java

feat/#82-delete-inventory -> develop
- 시재 삭제 기능을 구현하였습니다.
- 주석을 추가하였습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/82

feat: 시재 삭제 기능 추가

---

src/main/java/dnd/dnd10_backend/auth/domain/Token.java
src/main/java/dnd/dnd10_backend/auth/repository/TokenRepository.java
src/main/java/dnd/dnd10_backend/config/SecurityConfig.java
src/main/java/dnd/dnd10_backend/user/controller/TokenController.java
src/main/java/dnd/dnd10_backend/user/controller/UserController.java
src/main/java/dnd/dnd10_backend/user/domain/User.java
src/main/java/dnd/dnd10_backend/user/service/TokenService.java
src/main/java/dnd/dnd10_backend/user/service/UserService.java

feat/#83-kakao-logout -> develop
- 로그아웃 기능을 추가하였습니다
- 리프레쉬 토큰을 여러개 저장할 수 있도록 수정하였습니다.

feat: 로그아웃 기능 추가 및 토큰 기능 수정

---

src/main/java/dnd/dnd10_backend/user/controller/UserController.java
src/main/java/dnd/dnd10_backend/user/service/UserService.java

feat/#84-kakao-logout -> develop
- 로그아웃 버그로 인한 로그아웃 로직 순서를 번경하였습니다.

fix: 로그아웃 로직 순서 변경

---

src/main/java/dnd/dnd10_backend/Inventory/controller/InventoryController.java
src/main/java/dnd/dnd10_backend/Inventory/dto/response/InventoryRecordTodayResponseDto.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryRecordService.java
src/main/java/dnd/dnd10_backend/calendar/repository/TimeCardRepository.java

feat/#94-today-inven -> develop
- 오늘 시재 기록을 조회할 수 있는 기능을 구현하였습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/94

feat: 오늘 시재 기록 조회 기능 추가

---

src/main/java/dnd/dnd10_backend/board/service/BoardService.java

fix: all인지 확인하는 비교 연산 변경

---

src/main/java/dnd/dnd10_backend/Inventory/service/InventoryRecordService.java

feat/#94-today-inven -> develop
- 오늘 시재 기록 조회을 조건 수정하였습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/94

fix: 오늘 시재 기록 조회 수정

---

src/main/java/dnd/dnd10_backend/Inventory/service/InventoryRecordService.java

feat/#94-today-inven -> develop
- 오늘 시재 조회 순서를 변경하였습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/94

fix: 기록 조회 순서 변경

---

src/main/java/dnd/dnd10_backend/board/controller/BoardController.java
src/main/java/dnd/dnd10_backend/board/controller/CommentController.java
src/main/java/dnd/dnd10_backend/board/dto/response/PostResponseDto.java
src/main/java/dnd/dnd10_backend/board/repository/PostRepository.java
src/main/java/dnd/dnd10_backend/board/service/BoardService.java

게시글 검색 기능을 구현했습니다
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/31

feat: 게시글 검색 기능 개발

---

src/main/java/dnd/dnd10_backend/board/controller/BoardController.java
src/main/java/dnd/dnd10_backend/board/service/BoardService.java

fix: 조회수 방지 로직 수정

---

src/main/java/dnd/dnd10_backend/board/controller/BoardController.java
src/main/java/dnd/dnd10_backend/board/controller/CommentController.java
src/main/java/dnd/dnd10_backend/board/controller/NoticeController.java
src/main/java/dnd/dnd10_backend/board/domain/Notice.java
src/main/java/dnd/dnd10_backend/board/dto/request/CommentCreateDto.java
src/main/java/dnd/dnd10_backend/board/dto/response/CheckUserResponseDto.java
src/main/java/dnd/dnd10_backend/board/dto/response/NoticeResponseDto.java
src/main/java/dnd/dnd10_backend/board/repository/NoticeRepository.java
src/main/java/dnd/dnd10_backend/board/repository/PostCheckRepository.java
src/main/java/dnd/dnd10_backend/board/service/BoardService.java
src/main/java/dnd/dnd10_backend/board/service/NoticeService.java
src/main/java/dnd/dnd10_backend/common/domain/enums/CodeStatus.java
src/main/java/dnd/dnd10_backend/user/domain/User.java
src/main/resources/application.yml

게시글 작성, 댓글 멘션 시 알림 생성
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/31

feat: 게시글, 댓글 알림 기능 구현

---

src/main/java/dnd/dnd10_backend/board/controller/BoardController.java
src/main/java/dnd/dnd10_backend/board/controller/CommentController.java
src/main/java/dnd/dnd10_backend/board/service/BoardService.java
src/main/java/dnd/dnd10_backend/board/service/CommentService.java

- [] 기능 추가
게시글 댓글 타인 수정 금지 로직 추가
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/31

feat: 오타 수정, 게시글 댓글 타인 수정 금지 로직 추가

---

src/main/java/dnd/dnd10_backend/board/service/ImageService.java

fix: 파일 다운로드

---

src/main/java/dnd/dnd10_backend/board/service/ImageService.java

feat/#99-image -> feat/#99-image
- 파일 저장시 . 하나씩 더 저장되던거 수정 및 다운로드도 동일하게 변경

fix: 파일 다운로드 경로 변경

---

src/main/java/dnd/dnd10_backend/board/service/ImageService.java

fix: 로그찍기..

---

src/main/java/dnd/dnd10_backend/board/repository/ImageRepository.java
src/main/java/dnd/dnd10_backend/board/service/ImageService.java

feat/#99-image -> develop
- 이미지 중복 문제 해결 기능 및 삭제 기능을 추가하였습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/99

feat: 이미지 수정 시 이름 중복 문제 해결 기능 추가

---

src/main/java/dnd/dnd10_backend/Inventory/service/InventoryRecordService.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryService.java

fix/#111-time-error -> develop
- time error 해결하였습니다.

fix: time error 수정

---

src/main/java/dnd/dnd10_backend/board/controller/ImageController.java

fix: part -> path로 변경

---

src/main/java/dnd/dnd10_backend/board/domain/Comment.java
src/main/java/dnd/dnd10_backend/board/dto/request/CommentRequestDto.java
src/main/java/dnd/dnd10_backend/board/dto/response/CheckUserResponseDto.java

feat: userCode -> userProfileCode

---

src/main/java/dnd/dnd10_backend/user/dto/response/UserStoreResponseDto.java

chore: response 수정

---

src/main/java/dnd/dnd10_backend/board/controller/CommentController.java
src/main/java/dnd/dnd10_backend/board/dto/request/CommentRequestDto.java
src/main/java/dnd/dnd10_backend/board/dto/response/CheckUserResponseDto.java
src/main/java/dnd/dnd10_backend/board/service/BoardService.java
src/main/java/dnd/dnd10_backend/board/service/NoticeService.java

feat/#31-Board -> dev
userEmail -> userCode

fix: 알림 email로 찾기 -> userCode로 찾기

---

src/main/java/dnd/dnd10_backend/board/controller/BoardController.java
src/main/java/dnd/dnd10_backend/user/repository/UserRepository.java
src/main/java/dnd/dnd10_backend/user/service/UserService.java

fix: create post response 변경

---

src/main/java/dnd/dnd10_backend/board/domain/Comment.java
src/main/java/dnd/dnd10_backend/board/domain/Post.java
src/main/java/dnd/dnd10_backend/board/dto/response/CommentResponseDto.java
src/main/java/dnd/dnd10_backend/user/domain/User.java

fix: PostCheck 연관관계 수정

---

src/main/java/dnd/dnd10_backend/board/controller/BoardController.java
src/main/java/dnd/dnd10_backend/board/dto/response/PostSimpleResponseDto.java
src/main/java/dnd/dnd10_backend/user/repository/UserRepository.java
src/main/java/dnd/dnd10_backend/user/service/UserService.java

chore: board response 변경

---

src/main/java/dnd/dnd10_backend/board/controller/BoardController.java
src/main/java/dnd/dnd10_backend/board/repository/PostRepository.java
src/main/java/dnd/dnd10_backend/board/service/BoardService.java

내가 쓴 글 조회 기능 개발
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/31

feat: 내가 쓴 글 조회 기능 개발

---

src/main/java/dnd/dnd10_backend/board/controller/BoardController.java
src/main/java/dnd/dnd10_backend/board/service/ImageService.java

feat: 게시글 삭제 시 이미지 삭제 기능 구현

---

src/main/java/dnd/dnd10_backend/board/controller/BoardController.java
src/main/java/dnd/dnd10_backend/board/domain/Image.java
src/main/java/dnd/dnd10_backend/board/domain/Post.java
src/main/java/dnd/dnd10_backend/board/service/ImageService.java
src/main/java/dnd/dnd10_backend/checkList/domain/CheckList.java
src/main/java/dnd/dnd10_backend/checkList/dto/response/CheckListResponseDto.java
src/main/java/dnd/dnd10_backend/checkList/repository/CheckListRepository.java
src/main/java/dnd/dnd10_backend/checkList/service/CheckListService.java
src/main/java/dnd/dnd10_backend/checkList/service/DefaultCheckListService.java
src/main/java/dnd/dnd10_backend/config/jwt/JwtProperties.java
src/main/resources/application.yml

fix/#99-image-delete -> develop
- 이미지 삭제 기능에 대한 에러를 수정하였습니다.
- 토큰 만료기간을 수정하였습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/99

fix: 이미지 삭제 에러 수정

---

src/main/java/dnd/dnd10_backend/checkList/repository/CheckListRepository.java
src/main/java/dnd/dnd10_backend/checkList/service/CheckListService.java
src/main/java/dnd/dnd10_backend/checkList/service/DefaultCheckListService.java

fix/#29-check-date -> develop
- date 이름 에러 해결

fix: checkDate 이름 에러 해결

---

src/main/java/dnd/dnd10_backend/board/controller/ImageController.java
src/main/java/dnd/dnd10_backend/board/service/ImageService.java

feat/#99-image-modify -> develop
- 게시글 수정 시 이미지가 삭제되거나 추가되는 것에 대한 기능을 구현하였습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/99

feat: 게시글에서 이미지 수정 시 이미지 저장 및 삭제 기능 구현

---

src/main/java/dnd/dnd10_backend/board/service/ImageService.java

https://github.com/dnd-side-project/dnd-8th-10-backend/issues/99

fix: 이미지 수정 로직 변경

---

src/main/java/dnd/dnd10_backend/Inventory/service/InventoryService.java

fix/#111-timecard -> develop
- 시재 점검 시 근무 종료 시간에 대한 에러를 수정하였습니다.

fix: 시재 점검 시 시간 오류 수정

---

src/main/java/dnd/dnd10_backend/Inventory/service/InventoryRecordService.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryService.java

fix/#111-timecard -> develop
- 시재 점검 시간에 대한 오류를 수정하였습니다.
- 근무 종료시간이 오전 12시여서 발생하는 시재 점검 및 시재 기록 확인에 대한 오류를 모두 수정하였습니다.

fix: 시재 점검 오전 12시 에러 해결

---

src/main/java/dnd/dnd10_backend/Inventory/service/InventoryRecordService.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryService.java

fix/#111-timecard -> develop
- int형 month를 string형 month로 변경하였습니다.

fix: month 에러 해결

---

src/main/java/dnd/dnd10_backend/Inventory/service/InventoryRecordService.java
src/main/java/dnd/dnd10_backend/Inventory/service/InventoryService.java

fix/#111-day-length -> develop
- getDayOfMonth()시 한자리 날짜가 0없이 나와서 localdate format시 에러 발생한 거 수정했습니다.

fix: getMonth함수 관련 length수정

---

src/main/java/dnd/dnd10_backend/Inventory/service/InventoryRecordService.java

fix/#111-day-length -> develop
- 오늘 날짜 기준 수정했습니다.

fix: 오늘날짜 기준 수정

---

src/main/java/dnd/dnd10_backend/user/controller/UserController.java
src/main/java/dnd/dnd10_backend/user/service/TokenService.java
src/main/java/dnd/dnd10_backend/user/service/UserService.java

fix/#84-unlink -> develop
- 소셜 로그인시 탈퇴에 대한 부족한 로직을 추가하였습니다.

fix: 카카오 소셜 로그인 탈퇴 관련 에러 수정

---

src/main/java/dnd/dnd10_backend/user/service/UserService.java

fix/#84-unlink -> develop
- 로그아웃 및 탈퇴 관련 로직을 수정하였습니다.
- 로그아웃과 탈퇴 시 카카오와 통신하는 로직을 변경하였습니다.

fix: 로그아웃 및 탈퇴 관련 로직 수정

---

src/main/java/dnd/dnd10_backend/user/service/UserService.java

fix: 회원 탈퇴 관련 로직 수정중

---

src/main/java/dnd/dnd10_backend/user/controller/UserController.java
src/main/java/dnd/dnd10_backend/user/service/UserService.java

ex) fix/#84-unlink -> develop
- 회원 탈퇴 시 exception발생하는 오류를 수정했습니다.
- 로그아웃 시 앱 어드민 키 및 카카오 id를 사용하는 로직으로 수정하였습니다.
- 불필요한 코드를 삭제하였습니다.

fix: 회원 탈퇴 및 로그아웃 관련 로직 수정

---

src/main/java/dnd/dnd10_backend/board/controller/CommentController.java
src/main/java/dnd/dnd10_backend/board/domain/Notice.java
src/main/java/dnd/dnd10_backend/board/service/NoticeService.java

fix/#147-notice -> dev
댓글 작성시 게시글 작성자에게 알림 전송 기능 추가
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/147

fix: 댓글 작성시 알림 기능 추가 및 수정

---

src/main/java/dnd/dnd10_backend/board/dto/response/NoticeResponseDto.java
src/main/java/dnd/dnd10_backend/board/service/NoticeService.java

- [ㅌ] 버그 수정
feat/#147-notice -> dev
알림 res값을 수정했습니다
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/147

fix: res 값 수정

---

src/main/java/dnd/dnd10_backend/user/domain/User.java
src/main/java/dnd/dnd10_backend/user/repository/UserRepository.java
src/main/java/dnd/dnd10_backend/user/service/TokenService.java

fix/#132-kakao-email -> develop
- 카카오 소셜 회원가입시 이메일 미동의시 발생하는 에러를 해결했습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/132

fix: 카카오 소셜 회원가입 시 이메일 없는 경우 발생하는 에러

---

src/main/java/dnd/dnd10_backend/checkList/service/DefaultCheckListService.java
src/main/java/dnd/dnd10_backend/user/dto/response/UserResponseDto.java

fix/#154-check-scheduler -> develop
- 기본 체크리스트 생성 스케쥴러 동작 시 user의 workTime이 null인 경우 동작하지 않는 에러를 수정하였습니다.
- response 필드명을 통일하였습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/154

fix: 체크리스트 스케쥴러 에러

---

src/main/java/dnd/dnd10_backend/checkList/service/DefaultCheckListService.java

- 체크리스트 생성 스케쥴러의 동작 시간을 변경했습니다.

fix: 스케쥴러 시간대 변경

---

src/main/java/dnd/dnd10_backend/user/service/TokenService.java

develop -> upstream/develop
- 카카오 소셜로그인시 redirect-uri를 변경하였습니다.

fix: 소셜로그인 redirect-uri변경

---

src/main/java/dnd/dnd10_backend/user/controller/TokenController.java
src/main/java/dnd/dnd10_backend/user/service/TokenService.java

fix/#160-refresh-token -> develop
- 리프레시 토큰 발급시 바로 쿠키에 저장하도록 변경해주었습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/160

fix: 리프레시 토큰 쿠키 저장

---

src/main/java/dnd/dnd10_backend/user/controller/TokenController.java

fix/#160-refresh-token -> develop
- 쿠키 관련 설정을 변경하였습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/160

fix: 리프레시 토큰 쿠키 설정 수정

---

src/main/java/dnd/dnd10_backend/user/controller/TokenController.java

fix/#160-refresh-token -> develop
- 쿠키 수정으로 인한 리프레시 토큰 재발급 로직을 변경하였습니다.
- 쿠키의 maxAge를 설정하였습니다.
ex) https://github.com/dnd-side-project/dnd-8th-10-backend/issues/160

fix: 리프레시 토큰 재발 급 및 쿠키 age설정

---

src/main/java/dnd/dnd10_backend/user/controller/TokenController.java

fix/#160-refresh-token -> develop
- 쿠키의 maxAge를 수정하였습니다.
https://github.com/dnd-side-project/dnd-8th-10-backend/issues/160

fix:쿠키 maxAge수정

---

src/main/java/dnd/dnd10_backend/user/controller/TokenController.java

ex) https://github.com/dnd-side-project/dnd-8th-10-backend/issues/160

fix: 상태 원복

---

src/main/java/dnd/dnd10_backend/checkList/service/DefaultCheckListService.java

main -> main
- 코드 리팩토링을 하며 발생한 체크 리스트 생성이 안되는 오류를 해결하였습니다.

fix: 체크리스트 생성 오류 수정

---

src/main/java/dnd/dnd10_backend/Inventory/controller/InventoryController.java
src/main/java/dnd/dnd10_backend/board/controller/BoardController.java
src/main/java/dnd/dnd10_backend/board/controller/CommentController.java
src/main/java/dnd/dnd10_backend/board/controller/NoticeController.java
src/main/java/dnd/dnd10_backend/calendar/controller/CalendarController.java
src/main/java/dnd/dnd10_backend/calendar/controller/SalaryController.java
src/main/java/dnd/dnd10_backend/checkList/controller/CheckListController.java
src/main/java/dnd/dnd10_backend/checkList/service/DefaultCheckListService.java
src/main/java/dnd/dnd10_backend/common/service/ResponseService.java
src/main/java/dnd/dnd10_backend/store/controller/StoreController.java
src/main/java/dnd/dnd10_backend/user/controller/TokenController.java

main -> main
- ResponseService를 static class로 변경하였습니다.

fix: ResponseService static으로 변경

---

src/main/java/dnd/dnd10_backend/user/controller/UserController.java
src/main/java/dnd/dnd10_backend/user/repository/UserCacheRepository.java
src/main/java/dnd/dnd10_backend/user/repository/UserRepository.java

main -> main
- 사용자 정보 조회 시 store가 null인 정보를 fetch join할 때 발생하는 에러 해결

fix: store null시 fetch join에러

---

src/main/java/dnd/dnd10_backend/user/repository/UserCacheRepository.java
src/main/java/dnd/dnd10_backend/user/service/UserService.java

main -> main
- 사용자 정보 수정 시 Cache 업데이트 에러를 해결하였습니다.
-  Cacheput 에러를 해결하기 위해 사용자 정보 업데이트를 하는 메소드를 분리하였습니다.

fix: cache put시 발생하는 에러 해결
